travis:
  secure:
    BINSTAR_TOKEN: kQf5RIwB64Jhvumvp3DdrR2KDdhcIUXO5RADX+1XjZqNWk9tVX5pBCALt95T2yElSHG0nGU18FN9AHgF8Pj6FhS4XP/CiP2RuZrlEA65M46mZT65WSv5nz/01oXUbo+M2lRIMwvLSRsmUawYBHBfquLcbEWL7jJhDoiZl3srZ4L1bRA9vv/80DMBrhj2Hkgg+85tRBc402UzshKklnWzKZRDJ9T5i9cDgGiPvkSRIrqLu4UVviHoPBphHYc9+qOsNs0z2wNTqIuxKwwFLVN5tHJo5f95fS6stnN1BopAyUUva6fHWUZT8PWTSMBwM24QwNkcC/djmhlRwo9N0FMJeFMeVyQk8S3ZgKzgTGpW8xPTjiIWp0ZASwJpnNvQbe1OZjxLeRQztbGHepN4tJOgzFtFjivtQiRTRTu4N3ipxUWYIH3fz/UWuSw/fYD5cuRHg5I20Qey7pvG0bTXXVIwjwM5GKtP9W/C6PNCCtdOWFklGr9vtCupkcEA0iYYmRzMQsFZpGM54PBghT9iqnYstWNBZGjUFXcsFyTz9iubT98Vobj4tBQLFCvoa1dsAlZHyvB722yWUgFSCux9xYkAtDCX4zomAnZp+zIu1Bg52Oyk2F4UKkgzdVbQuT4B3NwN4CDlXt0gB+S0rJMEDlQ0aQksW7usqrMD4kMF63/VjjY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
